${NGINX_PROXY_OPTIONS}
include /etc/nginx/options.d/*.conf;
daemon ${NGINX_PROXY_DAEMON};
error_log ${NGINX_PROXY_ERROR_LOG} ${NGINX_PROXY_ERROR_LOG_LEVEL};
events {
  worker_connections ${NGINX_PROXY_WORKER_CONNECTIONS};
}
http {
  access_log ${NGINX_PROXY_ACCESS_LOG};
  charset ${NGINX_PROXY_CHARSET};
  include /etc/nginx/mime.types;
  server {
    listen ${NGINX_PROXY_PORT};
    listen [::]:${NGINX_PROXY_PORT} default_server;
    server_name ${NGINX_PROXY_SERVER_NAME};
    root ${NGINX_PROXY_ROOT};
    index ${NGINX_PROXY_INDEX};
    include /etc/nginx/server.d/*.conf;
    include /etc/nginx/conf.d/*.conf;
  }
}