# Deny access to htaccess and htpasswd files
location ~ /\.ht {
  deny  all;
}

# Deny access to hidden files (beginning with a period)
location ~ /\. {
  access_log off; log_not_found off; deny all;
}   
